name:                api-dotenv-request
version:             0.1.0.0
github:              "githubuser/api-dotenv-request"
license:             BSD-3-Clause
author:              "@juanfcarrillo"
maintainer:          "cmotoche@stackbuilders.com"
copyright:           "2023 @juanfcarrillo"
extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/api-dotenv-request#readme>

dependencies:
- base >= 4.7 && < 5
- dotenv
- req
- text
- aeson
- bytestring

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  api-dotenv-request-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api-dotenv-request

tests:
  api-dotenv-request-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api-dotenv-request
