name: Release package to Github

on:
  push:
    tags:
      - 'v*'
    branches:
      - chore/ci-update

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Haskell
        id: setup-haskell-cabal
        uses: haskell/actions/setup@v1
        with:
          ghc-version: "9.2"
          cabal-version: "3.6"
      - name: Build package
        id: build
        run: |
          cabal install --enable-executable-static
          tar -C $(cabal list-bin dotenv) -cvf dotenv-linux-x86_64-static.tar.gz dotenv
      - name: Create release with package assets
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            dotenv-linux-x86_64-static.tar.gz
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
