name: Release package to Github

on:
  push:
    tags:
      - 'v*'

jobs:
  build-binary:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ["8.10.1"]
        os: [ubuntu-latest , macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        id: setup-haskell-cabal
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: "2.4"
      - name: Build package
        id: build
        run: |
          cabal install
          if [ "$RUNNER_OS" == "Linux" ]; then
            tar -C dist/build/dotenv -cvf dotenv-linux-x86_64-static.tar.gz dotenv
          else
            tar -C dist/build/dotenv -cvf dotenv-osx-x86_64.tar.gz dotenv
          fi
      - name: Create release with package assets
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            dotenv-linux-x86_64-static.tar.gz
            dotenv-osx-x86_64.tar.gz
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
