name: Release package to Github

on:
  push:
    tags:
      - 'v*'
    branches:
      - chore/ci-update

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: addnab/docker-run-action@v3
        with:
          image: utdemir/ghc-musl:v24-ghc922
          options: -v ${{ github.workspace }}:/mnt
          run: |
            cd /mnt
            sh build.sh

      - name: Build package
        id: build
        run: |
          ls -lah
          ldd dotenv

      - name: Create release with package assets
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            dotenv
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
